/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Destruction Derby Raw)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80010C5Cu
#define func_80010C5C BootEntry  /* alias */
